#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// build.js — propagate the single canonical site nav into every content page.
//
// Source of truth: partials/nav.html. Edit the nav THERE, then run `npm run build`
// to sync all pages. Each page's nav is replaced between the
// <!-- nav:start --> … <!-- nav:end --> markers, with the correct item marked
// active for that page. Pages remain valid static HTML between builds.
//
// Quote forms and admin pages use a different header (no <nav>) and are skipped.
// ─────────────────────────────────────────────────────────────────────────────

const fs = require('fs');
const path = require('path');
const ROOT = path.join(__dirname, '..', 'public');         // pages live here
const PARTIAL = path.join(__dirname, '..', 'partials', 'nav.html'); // nav source

// Which nav item is active on each page.
//   top  → a top-level link;  btn+link → a dropdown toggle + its dropdown link.
const ACTIVE = {
  'home.html':                 { top: 'home.html' },
  'about.html':                { top: 'about.html' },
  'contact.html':              { top: 'contact.html' },
  'careers.html':              { top: 'careers.html' },
  'downloads.html':            { top: 'downloads.html' },
  'blogs.html':                { top: 'blogs.html' },
  'reviews.html':              { top: 'reviews.html' },
  'life-insurance.html':       { btn: 'Insurance', link: 'life-insurance.html' },
  'life-pension-products.html':{ btn: 'Insurance', link: 'life-pension-products.html' },
  'health-insurance.html':     { btn: 'Insurance', link: 'health-insurance.html' },
  'education-insurance.html':  { btn: 'Insurance', link: 'education-insurance.html' },
  'motor-insurance.html':      { btn: 'Insurance', link: 'motor-insurance.html' },
  'diaspora-insurance.html':   { btn: 'Insurance', link: 'diaspora-insurance.html' },
  'general-insurance.html':    { btn: 'Insurance', link: 'general-insurance.html' },
  'travel-insurance.html':     { btn: 'Insurance', link: 'travel-insurance.html' },
  'flying-doctors.html':       { btn: 'Services',  link: 'flying-doctors.html' },
  // faq.html, team.html carry the nav but are not nav items → no active mark.
};

const START_RE = /<!-- nav:start[\s\S]*?-->/;
const END = '<!-- nav:end -->';

// Remove all active marks and collapse nav-link alignment padding.
function stripActive(nav) {
  return nav
    .replace(/\s*class="active"/g, '')
    .replace(/class="nav-menu-btn active"/g, 'class="nav-menu-btn"')
    .replace(/(href="[^"]+")\s+>/g, '$1>');
}

// Apply the active mark for one page onto the clean canonical nav.
function withActive(nav, file) {
  const a = ACTIVE[file];
  if (!a) return nav;
  let out = nav;
  if (a.top)  out = out.replace(`<a href="${a.top}">`,  `<a class="active" href="${a.top}">`);
  if (a.link) out = out.replace(`<a href="${a.link}">`, `<a class="active" href="${a.link}">`);
  if (a.btn)  out = out.replace(
    `class="nav-menu-btn" type="button" aria-expanded="false">${a.btn}`,
    `class="nav-menu-btn active" type="button" aria-expanded="false">${a.btn}`);
  return out;
}

// Bootstrap partials/nav.html from home.html the first time.
function loadCanonical() {
  if (fs.existsSync(PARTIAL)) return fs.readFileSync(PARTIAL, 'utf8').trim();
  const home = fs.readFileSync(path.join(ROOT, 'home.html'), 'utf8');
  const s = home.indexOf('<nav');
  const e = home.indexOf('</nav>', s) + '</nav>'.length;
  if (s < 0 || e < 0) throw new Error('could not find <nav> in home.html to bootstrap partials/nav.html');
  const canon = stripActive(home.slice(s, e)) + '\n';
  fs.mkdirSync(path.dirname(PARTIAL), { recursive: true });
  fs.writeFileSync(PARTIAL, canon);
  console.log('bootstrapped partials/nav.html from home.html');
  return canon.trim();
}

function inject(html, navBlock) {
  const block = '<!-- nav:start (generated by build.js — edit partials/nav.html) -->\n' + navBlock + '\n' + END;
  const sm = html.match(START_RE);
  if (sm) {
    const s = sm.index;
    const e = html.indexOf(END, s) + END.length;
    return html.slice(0, s) + block + html.slice(e);
  }
  const ns = html.search(/<nav\b/);
  if (ns < 0) return null; // no marketing nav on this page
  const ne = html.indexOf('</nav>', ns) + '</nav>'.length;
  return html.slice(0, ns) + block + html.slice(ne);
}

const canonical = loadCanonical();
let changed = 0, skipped = 0;
for (const f of fs.readdirSync(ROOT).filter(x => x.endsWith('.html'))) {
  const p = path.join(ROOT, f);
  const html = fs.readFileSync(p, 'utf8');
  if (!/<nav\b/.test(html) && !START_RE.test(html)) { skipped++; continue; }
  const out = inject(html, withActive(canonical, f));
  if (out && out !== html) { fs.writeFileSync(p, out); changed++; console.log('  synced ' + f); }
}
console.log(`nav build: ${changed} page(s) updated, ${skipped} skipped (no marketing nav)`);
